### ISSUE TITLE
Creating an .srt subtitle time-stamp file

### ISSUE THREAD

**Issue by ghost** [mahimg/Speaker-recognition#6]
@mahimg @Souradip-sopho 
How can your software be used to create a .srt subtitle file?

**Comment by mahimg** [comment]
@MrOCR We had the subtitle info in a text file with us. We converted it into .srt format with the appropriate time interval using this [code](https://github.com/mahimg/Speaker-recognition/blob/master/Code/Unsupervised/Post-processing/srt.py)
